### ISSUE TITLE
(PYL-W0612) Unused variable found

### ISSUE THREAD

**Issue by mikeysan** [mikeysan/retweet_anything#13]
## Description
An unused variable takes up space in the code and can lead to confusion. It should be removed. If this variable is necessary, name the variable `_` or start the name with `unused` or `_unused`.

## Occurrences
There are 5 occurrences of this issue in the repository.

See all occurrences on DeepSource &rarr; [deepsource.io/gh/mikeysan/retweet_anything/issue/PYL-W0612/occurrences/](https://deepsource.io/gh/mikeysan/retweet_anything/issue/PYL-W0612/occurrences/)

## IMPORTANT
Please do not change anything other than the indicated issue. 
Use the link above to find all files and instances where the unused variable occurs. Example:
```
except tweepy.TweepError as e:
```

All you need to do is get rid of the `as e` so you end up with:
```
except tweepy.TweepError:
```

**Comment by jayesh-srivastava** [comment]
Hi I have made all the necessary changes and made the PR. All have been accepted except the one related to the file whoismikey-bot/twitterBot.py . Please can you review that PR and tell what's going wrong.

**Comment by mikeysan** [comment]
Thank you. All merged. I'm not sure what that one file was complaining about but I merged it anyway. I will take a look at deepsource to see if it gives me more detail later.
