### ISSUE TITLE
(FLK-W505) Doc line too long

### ISSUE THREAD

**Issue by mikeysan** [mikeysan/retweet_anything#19]
## Description
Docstring line lengths are recommended to be no greater than 79 characters.

## Occurrences
There is 1 occurrence of this issue in the repository.

See all occurrences on DeepSource &rarr; [deepsource.io/gh/mikeysan/retweet_anything/issue/FLK-W505/occurrences/](https://deepsource.io/gh/mikeysan/retweet_anything/issue/FLK-W505/occurrences/)

**Comment by jayesh-srivastava** [comment]
Hi. I have updated and made the PR. It has been accepted. The issue can be closed now : )
