### ISSUE TITLE
(FLK-W293) Blank line contains whitespace

### ISSUE THREAD

**Issue by mikeysan** [mikeysan/retweet_anything#20]
## Description
Blank lines should not contain any tabs or spaces.

## Occurrences
There are 2 occurrences of this issue in the repository.

See all occurrences on DeepSource &rarr; [deepsource.io/gh/mikeysan/retweet_anything/issue/FLK-W293/occurrences/](https://deepsource.io/gh/mikeysan/retweet_anything/issue/FLK-W293/occurrences/)

## Important
Only fix the issue reported (nothing more. no matter how obvious)

**Comment by osdev-in** [comment]
Hey @mikeysan , Can I work on this?

**Comment by jayesh-srivastava** [comment]
Hi. I have updated and made the PR. It has been accepted. This issue can be closed : )

**Comment by mikeysan** [comment]
There were some more.
