### ISSUE TITLE
(FLK-E302) Expected 2 blank lines

### ISSUE THREAD

**Issue by mikeysan** [mikeysan/retweet_anything#21]
## Description
Two blank lines are expected between functions and classes.

## Occurrences
There are 2 occurrences of this issue in the repository.

See all occurrences on DeepSource &rarr; [deepsource.io/gh/mikeysan/retweet_anything/issue/FLK-E302/occurrences/](https://deepsource.io/gh/mikeysan/retweet_anything/issue/FLK-E302/occurrences/)

## Important
ONLY fix the issue reported (no matter how obvious a different issue might be).

**Comment by jayesh-srivastava** [comment]
Hi. I have updated and made the PR. Both have been accepted. This issue can be closed.
