### ISSUE TITLE
(FLK-E211) Whitespace before opening parenthesis

### ISSUE THREAD

**Issue by mikeysan** [mikeysan/retweet_anything#22]
## Description
Open parentheses should not have any space before or after them.

## Occurrences
There is 1 occurrence of this issue in the repository.

See all occurrences on DeepSource &rarr; [deepsource.io/gh/mikeysan/retweet_anything/issue/FLK-E211/occurrences/](https://deepsource.io/gh/mikeysan/retweet_anything/issue/FLK-E211/occurrences/)

## Important
ONLY fix the issue reported (no matter how obvious a different issue might be).

**Comment by jayesh-srivastava** [comment]
Hi. I have updated and made the PR. But due to some reason, the checks are failing. Can you please review?

**Comment by mikeysan** [comment]
I'll review and if it relates to other issues, I'll merge it and raise a new issue for that new event.
