### ISSUE TITLE
(FLK-E128) Continuation line under-indented for visual indent

### ISSUE THREAD

**Issue by mikeysan** [mikeysan/retweet_anything#23]
## Description
A continuation line is under-indented for a visual indentation.

## Occurrences
There are 6 occurrences of this issue in the repository.

See all occurrences on DeepSource &rarr; [deepsource.io/gh/mikeysan/retweet_anything/issue/FLK-E128/occurrences/](https://deepsource.io/gh/mikeysan/retweet_anything/issue/FLK-E128/occurrences/)

## Important
ONLY fix the issue reported (no matter how obvious a different issue might be).

**Comment by jayesh-srivastava** [comment]
Can you please explain a bit as to what to fix. Do the lines need to be continuous or what?

**Comment by mikeysan** [comment]
@jayesh-srivastava Here is an example from one of the files. I have fixed this already for at least one file. But to explain the issue so you understand. Here is an example from one of the files.
Wrong code:

```py
24    auth = tweepy.OAuthHandler(consumer_key, consumer_secret)
25    auth.set_access_token(access_token, access_token_secret)
26    api = tweepy.API(auth, wait_on_rate_limit=True,
27        wait_on_rate_limit_notify=True)
28    try:
29        api.verify_credentials()
30    except Exception as e:
```
Correct code: note that I have moved the indentation on line 27.

```py
24    auth = tweepy.OAuthHandler(consumer_key, consumer_secret)
25    auth.set_access_token(access_token, access_token_secret)
26    api = tweepy.API(auth, wait_on_rate_limit=True,
27                     wait_on_rate_limit_notify=True)
28    try:
29        api.verify_credentials()
30    except Exception as e:
```
I hope this helps. 

Use this link (https://deepsource.io/gh/mikeysan/retweet_anything/issue/FLK-E128/occurrences/?page=1)  to find other instances where this happens. Ask me if you still need clarification.

**Comment by jayesh-srivastava** [comment]
Hi I made the necessary changes and made the PR @mikeysan
