### ISSUE TITLE
(FLK-W391) Multiple blank lines detected at end of the file

### ISSUE THREAD

**Issue by mikeysan** [mikeysan/retweet_anything#24]
## Description
There should be one, and only one, blank line at the end of each file. This warning will occur when there are two or more blank lines.

## Occurrences
There is 1 occurrence of this issue in the repository.

See all occurrences on DeepSource &rarr; [deepsource.io/gh/mikeysan/retweet_anything/issue/FLK-W391/occurrences/](https://deepsource.io/gh/mikeysan/retweet_anything/issue/FLK-W391/occurrences/)

## Important
ONLY fix the issue reported (no matter how obvious a different issue might be).

**Comment by jayesh-srivastava** [comment]
Updated and made the PR. The issue can be closed now : )
