### ISSUE TITLE
(FLK-E402) Module level import not at the top of the file

### ISSUE THREAD

**Issue by mikeysan** [mikeysan/retweet_anything#25]
## Description
All module level imports should be at the top of the file. This means that there should be no statements in between module level imports.

## Occurrences
There are 3 occurrences of this issue in the repository.

See all occurrences on DeepSource &rarr; [deepsource.io/gh/mikeysan/retweet_anything/issue/FLK-E402/occurrences/](https://deepsource.io/gh/mikeysan/retweet_anything/issue/FLK-E402/occurrences/)

## Important
ONLY fix the issue reported (no matter how obvious a different issue might be).

**Comment by divyanshu887** [comment]
@mikeysan i have send the PR(#28 ) for this issue please review it

**Comment by jayesh-srivastava** [comment]
Hi. I have updated and made the PRs. All have been accepted. The issue can be closed now : )
