### ISSUE TITLE
(FLK-E251) Unexpected spaces around keyword / parameter equals

### ISSUE THREAD

**Issue by mikeysan** [mikeysan/retweet_anything#26]
## Description
There should be no spaces before or after the `=` in a function definition.

## Occurrences
There are 8 occurrences of this issue in the repository.

See all occurrences on DeepSource &rarr; [deepsource.io/gh/mikeysan/retweet_anything/issue/FLK-E251/occurrences/](https://deepsource.io/gh/mikeysan/retweet_anything/issue/FLK-E251/occurrences/)

## Important
ONLY fix the issue reported (no matter how obvious a different issue might be).

## How to fix (example)

error: `lang = "en"`
fix:   `lang="en"`

**Comment by divyanshu887** [comment]
@mikeysan i have send the PR(#29 ) for this issue please review it

**Comment by jayesh-srivastava** [comment]
Hi. The PR related to https://github.com/mikeysan/retweet_anything/blob/master/phoducation-bot/phoducationBot.py has been made and accepted. 

The one related to https://github.com/mikeysan/retweet_anything/blob/master/tweetAnalysis/downloadTweets.py is showing 'checks failed'. Can you please review it?
