### ISSUE TITLE
(FLK-E225) Missing whitespace around operator

### ISSUE THREAD

**Issue by mikeysan** [mikeysan/retweet_anything#27]
## Description
There should be one space before and after all operators.

## Occurrences
There is 1 occurrence of this issue in the repository.

See all occurrences on DeepSource &rarr; [deepsource.io/gh/mikeysan/retweet_anything/issue/FLK-E225/occurrences/](https://deepsource.io/gh/mikeysan/retweet_anything/issue/FLK-E225/occurrences/)

## Important
ONLY fix the issue reported (no matter how obvious a different issue might be).

**Comment by divyanshu887** [comment]
@mikeysan i have send the PR(#28 ) for this issue please review it

**Comment by jayesh-srivastava** [comment]
Hi. I have updated and made the PR. It has been accepted. The issue can be closed now : )
