### ISSUE TITLE
(FLK-E211) Whitespace before opening parenthesis

### ISSUE THREAD

**Issue by mikeysan** [mikeysan/retweet_anything#45]
## Description
Open parentheses should not have any space before or after them.

## Occurrences
There is 1 occurrence of this issue in the repository.

See all occurrences on DeepSource &rarr; [deepsource.io/gh/mikeysan/retweet_anything/issue/FLK-E211/occurrences/](https://deepsource.io/gh/mikeysan/retweet_anything/issue/FLK-E211/occurrences/)

## Notes
Only make the change requested in this issue even if you see any other thing that you think needs fixing.

**Comment by guptasajal411** [comment]
Hey, can I work on this issue?

**Comment by mikeysan** [comment]
I'm not sure what this wasn't closed after merge.
