### ISSUE TITLE
(FLK-E305) Expected 2 blank lines after end of function or class

### ISSUE THREAD

**Issue by mikeysan** [mikeysan/retweet_anything#48]
## Description
Functions and classes should have two blank lines after them, separating them from other functions and classes.

## Occurrences
There is 1 occurrence of this issue in the repository.

See all occurrences on DeepSource &rarr; [deepsource.io/gh/mikeysan/retweet_anything/issue/FLK-E305/occurrences/](https://deepsource.io/gh/mikeysan/retweet_anything/issue/FLK-E305/occurrences/)

## Notes
Only change the issue describe in the issue. The link above will show you the file and what needs to be fixed.

**Comment by jayesh-srivastava** [comment]
Hey @mikeysan I have made the changes and made the PR. Please review it.
