### ISSUE TITLE
(FLK-E231) Missing whitespace after ',', ';', or ':'

### ISSUE THREAD

**Issue by mikeysan** [mikeysan/retweet_anything#5]
## Description
There should be whitespace after the characters `,`, `;`, and `:`.

## Occurrences
There are 5 occurrences of this issue in the repository.

See all occurrences on DeepSource &rarr; [deepsource.io/gh/mikeysan/retweet_anything/issue/FLK-E231/occurrences/](https://deepsource.io/gh/mikeysan/retweet_anything/issue/FLK-E231/occurrences/)

**Comment by jayesh-srivastava** [comment]
Hi, I've removed the whitespaces after ',' and create a PR.

**Comment by mikeysan** [comment]
Thank you.
