### ISSUE TITLE
(FLK-W391) Multiple blank lines detected at end of the file

### ISSUE THREAD

**Issue by mikeysan** [mikeysan/retweet_anything#50]
## Description
There should be one, and only one, blank line at the end of each file. This warning will occur when there are two or more blank lines.

## Occurrences
There is 1 occurrence of this issue in the repository.

See all occurrences on DeepSource &rarr; [deepsource.io/gh/mikeysan/retweet_anything/issue/FLK-W391/occurrences/](https://deepsource.io/gh/mikeysan/retweet_anything/issue/FLK-W391/occurrences/)

## Notes
Only change the issue describe in the issue. The link above will show you the file and what needs to be fixed.

**Comment by Naufal2511** [comment]
I am sorry, but I could not spot the file which has two blank likes or more at the end of the file, Can you please provide more details regarding the location of the file.
Thanks

**Comment by mikeysan** [comment]
Hi @Naufal2511 Did you follow the link in the issue?

This one: See all occurrences on DeepSource → [deepsource.io/gh/mikeysan/retweet_anything/issue/FLK-W391/occurrences/](https://deepsource.io/gh/mikeysan/retweet_anything/issue/FLK-W391/occurrences/)

When you follow that link it will show you the file as well as where the error is (not really an error in this case, though).

**Comment by sibteali786** [comment]
Hello! the issue is still opened and i have visited the link but there are no occurrences shown there. Kindly check if you have provided the right link. Thanks  
![image](https://user-images.githubusercontent.com/62849614/132281346-efdee1fc-0316-492a-854f-4ee7cf0840b0.png)

**Comment by mikeysan** [comment]
Hi @sibteali786 That might be my mistake. I fixed a number of these some time ago but didn't link them to the issue. Thanks for bring this to my attention. I will close it now.

**Comment by sibteali786** [comment]
That is totally fine. Thanks for replying.
