### ISSUE TITLE
(FLK-W291) Trailing whitespace detected

### ISSUE THREAD

**Issue by mikeysan** [mikeysan/retweet_anything#6]
## Description
There should be no whitespace after the final character in a line.

## Occurrences
There are 6 occurrences of this issue in the repository.

See all occurrences on DeepSource &rarr; [deepsource.io/gh/mikeysan/retweet_anything/issue/FLK-W291/occurrences/](https://deepsource.io/gh/mikeysan/retweet_anything/issue/FLK-W291/occurrences/)

**Comment by PracticalMetal** [comment]
HI, I would like to work on this, can you suggest me ways to get started?

**Comment by jayesh-srivastava** [comment]
Hey, I have removed the trailing whitespaces and created a PR.

**Comment by mikeysan** [comment]
Hi @PracticalMetal Jayesh has done a few of these but there are still some left. Follow this link https://deepsource.io/gh/mikeysan/retweet_anything/issue/FLK-W291/occurrences/ to see what's remaining and go for it.  The link will show you all the files and lines that have this issue. 

Do you know how to link an issue to a PR? Eddie showed me once before, but I can't remember.

I think you simply add a comment to your PR with a link to this issue. Please try that when you finish and we will both learn something if it works 😄

**Comment by jayesh-srivastava** [comment]
Hi, I have removed the leftover trailing whitespaces mentioned in
deepsource and created a PR. But the checks have failed, can you please
look into the matter and revert back. That would be great.
Best Regards,
Jayesh Srivastava.

**Comment by mikeysan** [comment]
Thank you :) I'll check and merge as soon as possible.
