### ISSUE TITLE
(FLK-W505) Doc line too long

### ISSUE THREAD

**Issue by mikeysan** [mikeysan/retweet_anything#7]
## Description
Docstring line lengths are recommended to be no greater than 79 characters.

## Occurrences
There are 8 occurrences of this issue in the repository.

See all occurrences on DeepSource &rarr; [deepsource.io/gh/mikeysan/retweet_anything/issue/FLK-W505/occurrences/](https://deepsource.io/gh/mikeysan/retweet_anything/issue/FLK-W505/occurrences/)

**Comment by jayesh-srivastava** [comment]
Hey, I have found all 8 occurrences where the number of characters are greater than 79.

**Comment by jayesh-srivastava** [comment]
What exactly is needed to be done with those lines?

**Comment by mikeysan** [comment]
I'm only seeing this now. I think the issues was resolved already, but we didn't attach this issue to it. I'll need to make a note about that later.

In the meantime, there are only two files left (if you click on the link above you will see them). The only thing that needs to be done is add the comment to multiple lines. Example:

This line:
```
# user.followers_count - no. of other users who are following this user (followers)
```
Could become:
```
# user.followers_count - no. of other users who are
# following this user (followers)
```

**Comment by mikeysan** [comment]
Resolved.
